services:
  blog:
    image: bazigan/blog
    build:
      context: ./blog
      dockerfile: Dockerfile
    init: true
    restart: always
    ports:
      - "80:5000"
    volumes:
      - blog-data:/app/blog/database.db

  monitoring:
    image: "louislam/uptime-kuma:1"
    init: true
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - monitoring:/data

volumes:
  blog-data: {}
  monitoring: {}
