version: '3.7'

services:
  blog:
    build: ./blog
    init: true
    restart: always
    ports:
      - "80:5000"
    volumes:
      - blog-data:/app/database.db

  monitoring:
    image: "louislam/uptime-kuma:1"
    init: true
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - monitoring:/app/data

volumes:
  - blog-data:
  - monitoring:
